### ISSUE TITLE
 Need help on using this package

### ISSUE THREAD

**Issue by shwethaGitHub-spec** [fivecar/react-native-background-downloader-queue#41]
HI,

I was looking for a proper documentation on how to use this package in js. But unable to find any help. Can you please help @fivecar . Request your help at the earliest. The example which is provided is type script one and isnt of any help to me as I need in js.

**Comment by fivecar** [comment]
The library's APIs work independently of Typescript vs. Javascript... if you want to use JS to consume the package, simply omit any Typescript type annotations from your code (basically, nearly all things with a colon and a type after them).

You'll find that nearly every Typescript library out there assumes it's clear how to use the same library in Javascript (i.e. by simply omitting type declarations). It unfortunately doesn't make sense for the documentation to repeat the exact same examples without types, because most people will find that information redundant...

**Comment by shwethaGitHub-spec** [comment]
I tried this unable to get the document downloaded...Can u please send a sample on how to download properly..

const dd = new DownloadQueue();
  await dd.init();
  console.log(dd);
  await dd.addUrl('https://example.com/boo.mp3');

  // This path will either be a local path if the file has been
  // downloaded. If not, you'll get the remote url.
  const localOrRemotePath = await dd.getAvailableUrl(
    'https://example.com/boo.mp3',
  );
  console.log(localOrRemotePath);

**Comment by fivecar** [comment]
@shwethaGitHub-spec : could you provide more of your code? The error you've reported is not possible to assess without the surrounding code that generated it. Could you show the lines above and below the DownloadQueue lines you've shown?

Also: extensions will download just fine. If you provide a full URL with extension, the file will be downloaded into a local file that retains that same extension.
